(()=>{
'use strict';
const BASE='/rebellious-youth/';
const bg=(name)=>BASE+name;
const portrait=(name)=>BASE+name;
const scenes={
1:{title:'KEY01｜比較好管的那個？',background:bg('scene-assets/office.jpeg'),steps:[
['旁白','門被推開的時候，林澈連頭都沒抬。'],['曾子豪｜zeng_normal','哈囉。'],['少年調查官','……你好。'],['曾子豪｜zeng_normal','你就是林澈那個少年調查官？'],['林澈｜lin_annoyed','什麼叫我的。'],['曾子豪｜zeng_normal','不然我要怎麼介紹？'],['曾子豪｜zeng_polite','我曾子豪。'],['曾子豪｜zeng_normal','叫我子豪就好。'],['旁白','他自己拉開椅子坐下。'],['旁白','熟練得不像第一次進這間辦公室。'],['少年調查官','最近有去學校嗎？'],['曾子豪｜zeng_polite','有啊。'],['少年調查官','每天？'],['曾子豪｜zeng_normal','……大部分？'],['曾子豪｜zeng_polite','我知道還是要穩定一點啦。'],['少年調查官','家裡呢？'],['曾子豪｜zeng_polite','還好。'],['曾子豪｜zeng_polite','我爸媽也有跟我談。'],['曾子豪｜zeng_polite','我有想過，以後不要再搞那麼大。'],['少年調查官','……'],['旁白','回答完整。'],['旁白','態度良好。'],['旁白','甚至知道什麼時候該補上一句反省。'],['曾子豪｜zeng_innocent','怎麼了？'],['少年調查官','沒有。'],['曾子豪｜zeng_normal','是不是覺得我很好聊？'],['林澈｜lin_annoyed','你少裝。'],['曾子豪｜zeng_innocent','我哪有。'],['少年調查官','你剛才說「不要再搞那麼大」。'],['曾子豪｜zeng_normal','嗯。'],['少年調查官','所以不是「不要再犯」？'],['曾子豪｜zeng_normal','……'],['曾子豪｜zeng_happy','你有在聽欸。'],['旁白','那一瞬間，你突然明白。'],['旁白','他不是比林澈更容易相信大人。'],['旁白','只是比林澈更知道，怎麼讓大人以為自己已經相信了。'],['SYSTEM','ZENG KEY01 COMPLETE']]},
2:{title:'KEY02｜你是哪種大人？',background:bg('scene-assets/office.jpeg'),steps:[['曾子豪｜zeng_normal','欸，我問你喔。'],['少年調查官','嗯？'],['曾子豪｜zeng_normal','如果我昨天十一點多才回家。'],['曾子豪｜zeng_innocent','這算很嚴重嗎？'],['少年調查官','為什麼十一點多？'],['曾子豪｜zeng_normal','就跟朋友在外面啊。'],['少年調查官','哪裡？'],['曾子豪｜zeng_happy','你看。'],['曾子豪｜zeng_normal','才講一句就開始問了。'],['少年調查官','是你自己問我的。'],['曾子豪｜zeng_normal','對啊。'],['曾子豪｜zeng_innocent','所以你覺得咧？'],['CHOICE','你怎麼回應？',[{label:'規則型',text:'你知道規定幾點以前要回去吧？',branch:[['曾子豪｜zeng_normal','知道啊。'],['曾子豪｜zeng_polite','下次會注意。'],['旁白','回答快得像是早就準備好了。']]},{label:'家長／管理型',text:'你爸媽知道嗎？這件事可能要跟他們確認。',branch:[['曾子豪｜zeng_normal','喔。'],['曾子豪｜zeng_polite','可以啊。'],['曾子豪｜zeng_normal','他們應該知道吧。'],['旁白','他答得很配合。'],['旁白','但原本翹著的腳放了下來。']]},{label:'過度寬鬆型',text:'十一點而已，有平安回去就好。',branch:[['曾子豪｜zeng_surprised','真的喔？'],['少年調查官','怎麼？'],['曾子豪｜zeng_happy','沒有。'],['曾子豪｜zeng_normal','你人滿好的。'],['旁白','不知道為什麼。'],['旁白','那句「人滿好的」，聽起來不像稱讚。']]},{label:'先理解情境型',text:'先告訴我，為什麼會到十一點。',branch:[['曾子豪｜zeng_normal','喔——'],['少年調查官','喔什麼？'],['曾子豪｜zeng_happy','沒有啊。'],['曾子豪｜zeng_normal','就記一下。'],['少年調查官','記什麼？'],['曾子豪｜zeng_innocent','秘密。']]}]],['旁白','曾子豪沒有再提那天到底為什麼晚回家。'],['旁白','你也不知道，剛才那個問題究竟是不是他真正想問的。'],['SYSTEM','ZENG KEY02 COMPLETE']]},
3:{title:'KEY03｜他的事你問他',background:bg('scene-assets/office.jpeg'),steps:[['少年調查官','林澈最近在學校怎麼樣？'],['曾子豪｜zeng_normal','你問他啊。'],['少年調查官','你們不是幾乎每天都在一起？'],['曾子豪｜zeng_normal','對啊。'],['少年調查官','所以——'],['曾子豪｜zeng_normal','所以我才不會跟你講。'],['少年調查官','……'],['曾子豪｜zeng_happy','不然我以後怎麼混。'],['CHOICE','你怎麼回應？',[{label:'轉向本人',text:'好，那不問他。你最近呢？',branch:[['曾子豪｜zeng_surprised','我？'],['少年調查官','嗯。'],['曾子豪｜zeng_normal','我又沒怎樣。'],['少年調查官','沒怎樣也可以問。'],['曾子豪｜zeng_normal','……你們很閒喔。']]},{label:'尊重友情界線',text:'知道了。我不會叫你替我盯著他。',branch:[['曾子豪｜zeng_normal','喔。'],['少年調查官','你是他朋友，不是我的線民。'],['曾子豪｜zeng_happy','線民也太難聽了吧。'],['少年調查官','所以不是。'],['曾子豪｜zeng_normal','……行。']]},{label:'問他的未來',text:'那你的事情可以問吧？你以後想做什麼？',branch:[['曾子豪｜zeng_surprised','蛤？'],['少年調查官','以後想做什麼？'],['曾子豪｜zeng_normal','不知道。'],['少年調查官','完全沒想過？'],['曾子豪｜zeng_normal','幹嘛一定要現在想。'],['曾子豪｜zeng_happy','我又不是明天就七十歲。']]},{label:'結束追問',text:'知道了。那就不問。',branch:[['曾子豪｜zeng_surprised','就這樣？'],['少年調查官','不然呢？'],['曾子豪｜zeng_normal','……沒有。'],['曾子豪｜zeng_happy','滿乾脆的。']]}]],['旁白','他守住了林澈的事。'],['旁白','但那天之後，你開始注意到另一件以前很容易被忽略的事。'],['旁白','曾子豪自己，也是正在接受保護管束的十七歲少年。'],['SYSTEM','ZENG KEY03 COMPLETE']]},
4:{title:'KEY04｜所以我那時候就知道了',background:bg('scene-assets/office.jpeg'),steps:[['少年調查官','最近學校怎麼樣？'],['曾子豪｜zeng_normal','還行啊。'],['少年調查官','家裡呢？'],['曾子豪｜zeng_normal','也還行。'],['少年調查官','你每次都還行。'],['曾子豪｜zeng_happy','那不是很好嗎？'],['少年調查官','你爸媽這次還是沒來？'],['曾子豪｜zeng_normal','忙啊。'],['少年調查官','你希望他們來嗎？'],['曾子豪｜zeng_normal','不用吧。'],['曾子豪｜zeng_normal','來了也不知道要講什麼。'],['少年調查官','曾子豪。'],['曾子豪｜zeng_normal','嗯？'],['少年調查官','你是不是很早就在判斷我是哪種大人？'],['曾子豪｜zeng_surprised','……'],['曾子豪｜zeng_happy','你現在才發現喔？'],['少年調查官','之前問我很晚回家那件事。'],['曾子豪｜zeng_normal','喔。'],['少年調查官','你故意問的？'],['曾子豪｜zeng_innocent','也沒有故意啦。'],['少年調查官','所以？'],['曾子豪｜zeng_happy','就想看看你會怎麼回啊。'],['KEY04_RECALL']]},
5:{title:'KEY05｜一通電話',background:bg('bg_ktv_room_night.png'),steps:[['旁白','晚上。'],['旁白','音樂唱到一半，隔壁突然傳來一聲巨響。'],['林澈｜lin_annoyed','又在吵。'],['曾子豪｜zeng_normal','唱你的啦。'],['旁白','第二聲比第一聲更近。'],['旁白','接著是玻璃碎掉的聲音。'],['林澈｜lin_guarded','……'],['曾子豪｜zeng_normal','我去看一下。'],['林澈｜lin_annoyed','你不要去湊熱鬧。'],['曾子豪｜zeng_normal','看出口啦。'],['旁白','門只開了一條縫。'],['旁白','走廊有人在罵。'],['旁白','有人被另一個人扶著，手臂和衣服上都是血。'],['曾子豪｜zeng_serious','……靠。'],['林澈｜lin_guarded','怎樣？'],['曾子豪｜zeng_serious','先不要出去。'],['旁白','他把門關回來。'],['林澈｜lin_guarded','後面不是有出口？'],['曾子豪｜zeng_serious','那邊也有人。'],['旁白','外面又是一聲碰撞。'],['林澈｜lin_guarded','報警？'],['曾子豪｜zeng_normal','店家應該報了。'],['旁白','曾子豪拿出手機。'],['林澈｜lin_surprised','你打給誰？'],['曾子豪｜zeng_normal','……'],['旁白','電話接通。'],['少年調查官｜電話','喂？'],['曾子豪｜電話','欸。'],['少年調查官｜電話','曾子豪？'],['曾子豪｜電話','你現在忙嗎？'],['少年調查官｜電話','怎麼了？'],['曾子豪｜電話','我們在唱歌。'],['少年調查官｜電話','……然後？'],['曾子豪｜電話','隔壁有人打起來。'],['曾子豪｜電話','有人流血。'],['旁白','電話另一頭安靜了一瞬間。'],['少年調查官｜電話','你們兩個有沒有受傷？'],['曾子豪｜電話','沒有。'],['少年調查官｜電話','現在在哪個包廂？'],['少年調查官｜電話','包廂號碼。'],['曾子豪｜電話','507。'],['少年調查官｜電話','門先鎖好。'],['少年調查官｜電話','不要出去看。'],['少年調查官｜電話','店家或警察叫你們撤離再走。'],['少年調查官｜電話','我現在過去。'],['曾子豪｜電話','……喔。'],['旁白','電話掛掉。'],['林澈｜lin_surprised','他真的要來？'],['曾子豪｜zeng_normal','他自己說的啊。'],['林澈｜lin_normal','喔。'],['旁白','等現場終於安靜下來時，警察已經到了。'],['旁白','你在人群外找到兩個少年。'],['旁白','一路跑上樓，連呼吸都還沒喘勻。'],['少年調查官','有沒有受傷？'],['林澈｜lin_normal','沒有。'],['少年調查官','曾子豪？'],['曾子豪｜zeng_surprised','……'],['少年調查官','怎麼了？'],['曾子豪｜zeng_happy','沒有。'],['曾子豪｜zeng_happy','就覺得滿神奇的。'],['少年調查官','什麼？'],['曾子豪｜zeng_normal','竟然真的會有人因為一通電話——'],['曾子豪｜zeng_happy','跑得滿頭大汗。'],['少年調查官','……'],['林澈｜lin_annoyed','你現在還有心情笑喔。'],['曾子豪｜zeng_happy','不然咧。'],['少年調查官','先下樓。'],['曾子豪｜zeng_normal','喔。'],['旁白','他把手機收回口袋。'],['旁白','這一次，他沒有說「其實不用來」。'],['SYSTEM','ZENG KEY05 COMPLETE'],['SYSTEM','ZENG SERIES COMPLETE']]}
};
const key04Recall={A:[['曾子豪｜zeng_normal','你那時候第一句就問我知不知道規定。'],['少年調查官','你本來就知道。'],['曾子豪｜zeng_happy','對啊。'],['曾子豪｜zeng_normal','所以我那時候就知道了。'],['少年調查官','知道什麼？'],['曾子豪｜zeng_polite','你是那種規定先講完，後面再說的大人。'],['少年調查官','評價很差？'],['曾子豪｜zeng_normal','沒有啊。'],['曾子豪｜zeng_happy','至少很好預測。'],['曾子豪｜zeng_normal','知道你會先問什麼，就知道要先回答什麼。']],B:[['曾子豪｜zeng_normal','你那時候馬上就問我爸媽知不知道。'],['少年調查官','嗯。'],['曾子豪｜zeng_normal','我那時候就在想。'],['少年調查官','想什麼？'],['曾子豪｜zeng_happy','以後有些事不要跟你講太細。'],['少年調查官','因為我可能聯絡你爸媽？'],['曾子豪｜zeng_normal','不是不能聯絡。'],['曾子豪｜zeng_normal','是我才講第一句，你就已經想到他們了。'],['曾子豪｜zeng_happy','那我當然也要想一下，我下一句要不要講啊。']],C:[['曾子豪｜zeng_happy','你那時候最好笑。'],['少年調查官','哪裡？'],['曾子豪｜zeng_normal','我說十一點多回家。'],['曾子豪｜zeng_normal','你直接跟我說平安就好。'],['少年調查官','……'],['曾子豪｜zeng_happy','我那時候就在想。'],['曾子豪｜zeng_innocent','這個是不是太好講話了？'],['少年調查官','所以你說我「人滿好的」。'],['曾子豪｜zeng_happy','對啊。'],['曾子豪｜zeng_normal','可是太好講話也不一定有用。'],['少年調查官','什麼意思？'],['曾子豪｜zeng_normal','真的出事的時候，我要找的是會處理的人。']],D:[['曾子豪｜zeng_normal','你那時候沒有先罵我。'],['少年調查官','嗯。'],['曾子豪｜zeng_normal','也沒有先說沒關係。'],['少年調查官','所以？'],['曾子豪｜zeng_happy','很麻煩。'],['少年調查官','……這算稱讚？'],['曾子豪｜zeng_happy','因為這種最難準備答案啊。'],['曾子豪｜zeng_normal','我要先跟你講發生什麼。'],['曾子豪｜zeng_normal','你才決定要不要管。'],['少年調查官','不好嗎？'],['曾子豪｜zeng_happy','……還行啦。']]};
const key04Common=[['少年調查官','所以你一直都在測我？'],['曾子豪｜zeng_normal','也沒有一直。'],['少年調查官','偶爾？'],['曾子豪｜zeng_happy','看情況。'],['少年調查官','累不累？'],['曾子豪｜zeng_normal','還好。'],['少年調查官','又是還好。'],['曾子豪｜zeng_happy','很好用啊。']];
const key04TrustExtra=[['曾子豪｜zeng_normal','……我爸上次去學校。'],['曾子豪｜zeng_normal','好像國中了吧。'],['少年調查官','很久了。'],['曾子豪｜zeng_normal','還好吧。'],['曾子豪｜zeng_normal','反正成績不要太難看。'],['曾子豪｜zeng_normal','不要又搞到法院。'],['曾子豪｜zeng_normal','他們其實也不太管。'],['少年調查官','你喜歡這樣？'],['曾子豪｜zeng_normal','滿爽的啊。'],['旁白','他停了一下。'],['曾子豪｜zeng_normal','……真的。'],['旁白','你沒有追問。'],['旁白','這一次，他也沒有立刻把話題轉回林澈身上。']];
const spriteMap={'zeng_normal':'character/zeng/zeng_normal_t2.png','zeng_polite':'character/zeng/zeng_polite_t2.png','zeng_innocent':'character/zeng/zeng_innocent_t2.png','zeng_happy':'character/zeng/zeng_happy_t2.png','zeng_surprised':'character/zeng/zeng_shock_t2.png','zeng_serious':'character/zeng/zeng_serious_t2.png','lin_annoyed':'scene-assets/lin-annoyed-transparent.png','lin_guarded':'scene-assets/lin-annoyed-transparent.png','lin_surprised':'scene-assets/lin-annoyed-transparent.png','lin_normal':'scene-assets/lin-annoyed-transparent.png'};
function start(id){
 const s=scenes[id];if(!s)return;document.body.innerHTML='';
 const root=document.createElement('main');root.style=`position:fixed;inset:0;background:#07111c center/cover no-repeat;color:#f5f2ea;font-family:system-ui,-apple-system,'Noto Sans TC',sans-serif;overflow:hidden;`;root.style.backgroundImage=`linear-gradient(#06101a66,#06101a66),url(${s.background})`;
 const title=document.createElement('div');
 const parts=s.title.split('｜');
 title.innerHTML=`<div style="border-left:7px solid #ff6b35;padding-left:18px"><div style="color:#f59b70;font-size:clamp(13px,2.6vw,20px);font-weight:700;letter-spacing:.22em;margin-bottom:8px">FRIEND ZENG ${parts[0]}</div><div style="font-size:clamp(34px,8vw,66px);font-weight:700;line-height:1.12;letter-spacing:.02em;text-shadow:0 2px 8px #0008">${parts[1]||''}</div></div>`;
 title.style='position:absolute;left:6vw;top:5vh;z-index:3;max-width:88vw';root.append(title);
 const char=document.createElement('img');char.style='display:none;position:absolute;left:50%;bottom:0;transform:translateX(-50%);height:78vh;max-width:82vw;object-fit:contain;object-position:bottom;z-index:1;pointer-events:none';root.append(char);
 const box=document.createElement('section');box.style='position:absolute;left:4vw;right:4vw;bottom:6vh;min-height:22vh;background:#071827ee;border:2px solid #64798d;padding:56px 30px 26px;box-sizing:border-box;z-index:4;box-shadow:0 10px 28px #0007';root.append(box);document.body.append(root);
 let i=0;
 function setDialogueBox(){box.style.left='4vw';box.style.right='4vw';box.style.top='auto';box.style.bottom='6vh';box.style.transform='none';box.style.minHeight='22vh';box.style.textAlign='left';box.style.padding='56px 30px 26px';}
 function setNarrationBox(){box.style.left='10vw';box.style.right='10vw';box.style.top='50%';box.style.bottom='auto';box.style.transform='translateY(-50%)';box.style.minHeight='0';box.style.textAlign='center';box.style.padding='28px 30px';}
 function speakerTab(name){return `<div style="position:absolute;left:-2px;top:-54px;min-width:210px;padding:15px 28px;background:#0b2234;border:2px solid #64798d;border-bottom:none;color:#f7f7f5;font-size:clamp(18px,4vw,28px);font-weight:700;letter-spacing:.04em;box-sizing:border-box">${name}</div>`;}
 function continueMark(){return `<small style="position:absolute;right:26px;bottom:20px;color:#e3a06d;font-size:clamp(13px,2.8vw,17px);font-weight:700">點擊繼續　→</small>`;}
 function setSprite(label){const m=label.match(/｜(zeng_[a-z]+|lin_[a-z]+)/);if(!m){char.style.display='none';return;}const f=spriteMap[m[1]];if(!f){char.style.display='none';return;}char.src=portrait(f);char.style.display='block';}
 function render(){
  if(i>=s.steps.length){setDialogueBox();box.innerHTML=speakerTab('SYSTEM')+'<p style="font-size:clamp(20px,4.5vw,30px);margin:0">KEY 測試完成。</p>';char.style.display='none';return;}
  const st=s.steps[i];
  if(st[0]==='KEY04_RECALL'){const qs=new URLSearchParams(location.search);let choice=(qs.get('choice')||localStorage.getItem('zeng_key02_choice')||'D').toUpperCase();if(!key04Recall[choice])choice='D';const trust=qs.get('trust')==='1'||localStorage.getItem('trust_key04_complete')==='true'||localStorage.getItem('TRUST_KEY04_COMPLETE')==='true';const insert=[...key04Recall[choice],...key04Common,...(trust?key04TrustExtra:[]),['SYSTEM','ZENG KEY04 COMPLETE']];s.steps.splice(i,1,...insert);render();return;}
  if(st[0]==='CHOICE'){setDialogueBox();char.style.display='none';box.style.paddingTop='34px';box.innerHTML=`<div style="color:#f59b70;font-size:clamp(14px,3vw,18px);font-weight:700;letter-spacing:.14em;margin-bottom:12px">PLAYER CHOICE</div><p style="font-size:clamp(20px,4.5vw,28px);margin:0 0 18px">${st[1]}</p>`;st[2].forEach((opt,n)=>{const b=document.createElement('button');b.innerHTML=`<strong>${String.fromCharCode(65+n)}.</strong> ${opt.text}`;b.style='display:block;width:100%;margin:10px 0;padding:14px 16px;text-align:left;background:#10283a;color:#fff;border:1px solid #667b8e;font-size:clamp(15px,3.6vw,20px);line-height:1.45';b.onclick=e=>{e.stopPropagation();const choice=String.fromCharCode(65+n);if(id===2)localStorage.setItem('zeng_key02_choice',choice);if(id===3)localStorage.setItem('zeng_key03_choice',choice);s.steps.splice(i+1,0,...opt.branch);i++;render()};box.append(b)});return;}
  if(st[0]==='旁白'){char.style.display='none';setNarrationBox();box.innerHTML=`<p style="margin:0;font-size:clamp(20px,4.7vw,30px);line-height:1.8;letter-spacing:.04em">${st[1]}</p>${continueMark()}`;return;}
  setDialogueBox();setSprite(st[0]);
  if(st[0]==='SYSTEM'){localStorage.setItem(`zeng_key0${id}_complete`,'true');if(st[1]==='ZENG SERIES COMPLETE')localStorage.setItem('zeng_series_complete','true');box.innerHTML=speakerTab('SYSTEM')+`<p style="font-size:clamp(20px,4.5vw,30px);margin:0">${st[1]}</p>${continueMark()}`;return;}
  const speaker=st[0].split('｜')[0];box.innerHTML=speakerTab(speaker)+`<p style="font-size:clamp(20px,4.7vw,30px);line-height:1.55;margin:0 0 28px">${st[1]}</p>${continueMark()}`;
 }
 root.onclick=()=>{if(s.steps[i]?.[0]==='CHOICE')return;i++;render()};render();
}
const q=new URLSearchParams(location.search);const id=Number(q.get('zeng'));if(id>=1&&id<=5)start(id);
})();